export const Menu = [
    {
      id: 1,
      title: "Pad Kha Pao",
      title1: "ဖက်ကဖောင်းဟင်း",
      main_category: "food",
      category: ["rice", "food"],
      price: "10,000",
      img: "./img/food/rice/1.jpg",
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 2,
      title: "Rice & Chicken Curry",
      title1: "ကြက်သားနှင့် ထမင်း",
      main_category: "food",
      category: ["rice", "food"],
      price: "12,000",
      img: "./img/food/rice/2.jpg",
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 3,
      title: "Fried Rice Chicken/Pork",
      title1: "ထမင်းကြော် (ကြက်/ဝက်)",
      main_category: "food",
      category: ["rice", "food"],
      price: "7,500",
      img: "./img/food/rice/3.jpg",
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 4,
      title: "Fried Mustard Pickle Chicken/Pork",
      title1: "မုန့်ညှင်းချဉ်ကြော် (ကြက်/ဝက်)",
      main_category: "food",
      category: ["curry", "food"],
      price: "13,000",
      img: "./img/food/curry/1.jpg",
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 5,
      title: "Sweet & Sour Chicken/Pork",
      title1: "ကြက်/ဝက် ချိုချဉ်ကြော်",
      main_category: "food",
      category: ["curry", "food"],
      price: "12,000",
      img: "./img/food/curry/2.jpg",
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 6,
      title: "Streamed Pork Belly with Black Mushroom",
      title1: "မှိုမဲ ဝက်သုံးထပ်သားပေါင်း",
      main_category: "food",
      category: ["curry", "food"],
      price: "16,000",
      img: "./img/food/curry/3.jpg",
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 7,
      title: "Fried Flat Noodle with Kailan Chicken/Pork",
      title1: "ကိုက်လန်ခေါက်ဆွဲပြားကြော်(ကြက်/ဝက်)",
      main_category: "food",
      category: ["noodle", "food"],
      price: "7,500",
      img: "./img/food/noodle/1.jpg",
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: "Fried Noodle Chicken/Pork",
      title1: "ခေါက်ဆွဲကြော်",
      main_category: "food",
      category: ["noodle", "food"],
      price: "7,500",
      img: "./img/food/noodle/2.jpg",
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: "Nangyi Salad",
      title1: "နန်းကြီးသုပ်",
      main_category: "food",
      category: ["noodle", "salad", "food"],
      price: "5,000",
      img: "./img/food/noodle/3.jpg",
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 10,
      title: "Spaghetti Carbonara",
      title1: "စပါဂတ်တီ",
      main_category: "food",
      category: ["noodle", "food"],
      price: "12,000",
      img: "./img/food/noodle/4.jpg",
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 11,
      title: "Spaghetti Marinara",
      title1: "စပါဂတ်တီ",
      main_category: "food",
      category: ["noodle", "food"],
      price: "12,000",
      img: "./img/food/noodle/5.jpg",
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 12,
      title: "Spaghetti Aglio",
      title1: "စပါဂတ်တီ",
      main_category: "food",
      category: ["noodle", "food"],
      price: "12,000",
      img: "./img/food/noodle/6.jpg",
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 13,
      title: "Mote Hnin Khar",
      title1: "မုန့်ဟင်းခါး",
      main_category: "food",
      category: ["noodle", "soup", "food"],
      price: "4,500",
      img: "./img/food/noodle/7.jpg",
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 14,
      title: "Coconut Noodle",
      title1: "အုန်းနို့ခေါက်ဆွဲ",
      main_category: "food",
      category: ["noodle", "soup", "food"],
      price: "4,500",
      img: "./img/food/noodle/8.jpg",
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 15,
      title: "Beef Burger",
      title1: "အမဲသားဘာဂါ",
      main_category: "food",
      category: ["bread", "food"],
      price: "15,000",
      img: "./img/food/bread/1.jpg",
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 16,
      title: "Hot Dog",
      title1: "ဟော့ဒေါ့",
      main_category: "food",
      category: ["bread", "food"],
      price: "7,500",
      img: "./img/food/bread/2.jpg",
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 17,
      title: "Grill & Cheese Sandwich",
      title1: "ချိစ် ပါမုန့်ကင်",
      main_category: "food",
      category: ["bread", "food"],
      price: "7,500",
      img: "./img/food/bread/3.jpg",
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 18,
      title: "Cheese Sandwich",
      title1: "ချိစ် ပါမုန့်",
      main_category: "food",
      category: ["bread", "food"],
      price: "7,000",
      img: "./img/food/bread/4.jpg",
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 19,
      title: "Club Sandwich",
      title1: "အသားညှပ်ပေါင်မုန့်",
      main_category: "food",
      category: ["bread", "food"],
      price: "8,500",
      img: "./img/food/bread/5.jpg",
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 20,
      title: "Fried Chicken Wing",
      title1: "ကြက်တောင်ပံကျွတ််ကျွတ်ကြော်",
      main_category: "food",
      category: ["deep-fried", "food"],
      price: "12,000",
      img: "./img/food/deepfried/1.jpg",
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 21,
      title: "Vegetable Spring Rool",
      title1: "ကော်ပြန့်လိပ်",
      main_category: "food",
      category: ["deep-fried", "food"],
      price: "7,000",
      img: "./img/food/deepfried/2.jpg",
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 22,
      title: "Panko Chicken",
      title1: "ကြက်သားမုန့်ကပ်ကြော်",
      main_category: "food",
      category: ["deep-fried", "food"],
      price: "12,000",
      img: "./img/food/deepfried/3.jpg",
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 23,
      title: "Thai Papaya Salad",
      title1: "သင်္ဘောသီးထောင်း",
      main_category: "food",
      category: ["salad", "food"],
      price: "5,000",
      img: "./img/food/salad/1.jpg",
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 24,
      title: "Loh Mee (Kaw Ye Noodle) Chicken/Pork",
      title1: "ကော်ရည်ခေါက်ဆွဲ (ကြက်/ဝက်)",
      main_category: "food",
      category: ["soup", "noodle", "food"],
      price: "4,500",
      img: "./img/food/soup/1.jpg",
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 24,
      title: "Tom Yum Soup Prawn",
      title1: "ပုဇွန် တုန်ယမ်းဟင်းရည်",
      main_category: "food",
      category: ["soup", "food"],
      price: "11,000",
      img: "./img/food/soup/2.jpg",
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 25,
      title: "Ice Americano",
      title1: "ပုဇွန် တုန်ယမ်းဟင်းရည်",
      main_category: "drink",
      category: ["coffee", "drink"],
      price: "11,000",
      img: "./img/drink/cold/coffee/1.jpg",
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 26,
      title: "Ice Mocha",
      title1: "ပုဇွန် တုန်ယမ်းဟင်းရည်",
      main_category: "drink",
      category: ["coffee", "drink"],
      price: "11,000",
      img: "./img/drink/cold/coffee/2.jpg",
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 27,
      title: "Ice Strawberry",
      title1: "ပုဇွန် တုန်ယမ်းဟင်းရည်",
      main_category: "drink",
      category: ["other", "drink"],
      price: "11,000",
      img: "./img/drink/cold/other/1.jpg",
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
];